version: "3"
services:
  server:
    build:
      context: .
      args:
        IMAGE: gcr.io/amplication/app-node
    ports:
      - "${SERVER_PORT}:3000"
    environment:
      POSTGRESQL_URL: "postgres://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@db:5432"
    depends_on:
      - migrate
  migrate:
    build:
      context: .
      args:
        IMAGE: gcr.io/amplication/app-node
    command: npm run db:init
    environment:
      POSTGRESQL_URL: "postgres://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@db:5432"
    depends_on:
      - db
  db:
    image: postgres:12
    ports:
      - "${POSTGRESQL_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
