name: Docker CD

on:
  push:
    branches: [master]

jobs:
  scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./packages/amplication-scheduler
          file: ./packages/amplication-scheduler/Dockerfile
          pull: true
          push: true
          cache-from: type=registry,ref=amplication/amplication:latest
          cache-to: type=inline
          tags: amplication/amplication:latest
    timeout-minutes: 2
