# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Fetch master
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/master:refs/remotes/origin/master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Update npm
        run: npm i -g npm@7
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npm run bootstrap -- --loglevel verbose
      - run: npm run prisma:generate
      - name: Define Lerna since parameter
        run: echo "SINCE=origin/master" >> $GITHUB_ENV
        if: ${{ github.ref != 'refs/heads/master' }}
      - run: npm run check-format -- --since $SINCE
      - run: npm run build -- --include-dependencies --include-dependents --since $SINCE
      - run: npm run lint -- --since $SINCE --include-dependents
      - run: npm run check-graphql-schema -- --since $SINCE
      - run: npm test -- --since $SINCE --ignore @amplication/e2e-tester

    timeout-minutes: 30
